chore(commitlint): print msg on failure
This commit adds some logic to the commit-msg git hook, so that on
failure it also prints the failing commit message. This is useful in
order to firther edit the failing msg and not having to write it again
from the top.

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -5,4 +5,11 @@
 # status after issuing an appropriate message if it wants to stop the
 # commit.  The hook is allowed to edit the commit message file.
 
-cat "$1" | ./node_modules/.bin/commitlint
+./node_modules/.bin/commitlint --edit "$1"
+lint_exit="$?"
+
+if [[ "$lint_exit" -ne 0 ]]; then
+    echo -e "Failing commit msg:\n"
+    cat "$1"
+    exit "$lint_exit"
+ fi
